"""empty message

Revision ID: 6e2452de5345
Revises: 
Create Date: 2020-02-17 16:49:47.165448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2452de5345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('layer_type', sa.String(length=64), nullable=True),
    sa.Column('meta_name', sa.String(length=128), nullable=True),
    sa.Column('meta_kind', sa.String(length=128), nullable=True),
    sa.Column('meta_org', sa.String(length=256), nullable=True),
    sa.Column('meta_updated', sa.String(length=128), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('opacity', sa.DECIMAL(precision=1, scale=1), nullable=False),
    sa.Column('isqueryable', sa.Boolean(), nullable=True),
    sa.Column('isgeojson', sa.Boolean(), nullable=False),
    sa.Column('isPopup', sa.Boolean(), nullable=True),
    sa.Column('layer_name', sa.String(length=128), nullable=True),
    sa.Column('_popup_attributes', sa.String(length=250), nullable=True),
    sa.Column('_search_fields', sa.String(length=250), nullable=True),
    sa.Column('projection', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('legend_url', sa.String(length=600), nullable=True),
    sa.Column('server_type', sa.String(length=50), nullable=False),
    sa.Column('closed_dataset', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('authkey', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer_id')
    )
    op.create_index(op.f('ix_layers_ordering'), 'layers', ['ordering'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_layers_ordering'), table_name='layers')
    op.drop_table('layers')
    # ### end Alembic commands ###
